resources:
  - ../../base/apps
  - ../../base/projects
  - ../../base/repositories

patches:
  - target:
      kind: Application
      name: core-app
    path: set_core_app_labels.yaml
  - target:
      kind: Application
      name: core-app
    path: set_sync_policy.yaml
  - target:
      kind: Application
      name: core-app
    path: child_apps_source.yaml
  - target:
      kind: Application
      name: core-app
    path: cluster_destination.yaml
